### ISSUE TITLE
Example of using the trivia class?

### ISSUE THREAD

**Issue by willthames** [munen/p_slides#10]
Hi, I see in themes/zhaw/zhaw.css there is a `.trivia` class that looks useful for some local theming. 

I've tried a few approaches in and out of the `<slides>` section but can't really work out how to make use of it.

**Comment by munen** [comment]
Hi @willthames 

I do apologize for not getting to you in such a long time. I must have overseen the Github notification mail. I'm happy to show you an example! This is from the slide-deck that I am actually writing just now(;

```markdown
# TDD (Test Driven Development)

## Recap

* In Web2, you learned about the TDD and BDD processes
* You used the Jasmine Framework for that

<h2 class="trivia"></h2>

Can you explain what TDD/BDD means?

```

![trivia_example](https://cloud.githubusercontent.com/assets/505721/19629148/7123d6ea-996e-11e6-8c62-3ea3e24dd631.png)

**Comment by munen** [comment]
@willthames I'll close this issue, because I answered it. If you have any further questions, though. Please feel free to shoot me a mail or re-open this issue!
