### ISSUE TITLE
Export to PDF appears to work ok in Firefox

### ISSUE THREAD

**Issue by amundo** [munen/p_slides#4]
Background colors of the header are showing up for me now, here’s a screenshot of the PDF exported in FF:

<img width="954" alt="screen shot 2016-07-12 at 1 23 38 pm" src="https://cloud.githubusercontent.com/assets/30924/16782326/e7953436-4833-11e6-931a-312e44fb6252.png">

**Comment by munen** [comment]
@amundo Thx for checking it out! You are absolutely right - by now it seems to work just fine. I actually updated the comment about an hour ago^_^

https://github.com/munen/p_slides/commit/da67d744555a87a401159ea5973c4186551576cc
